d<?php


include_once($_SERVER['DOCUMENT_ROOT'] . '/wp-config.php');


$return = '';
if (count($_REQUEST) > 0) {
  foreach ($_REQUEST as $type => $item) {

    if ($type == 'xml_url' || $type == 'api_key') {
      global $wpdb;
      $table_name = $wpdb->prefix . "mapgroove";
      if ( $savedfile && ! isset( $savedfile['error'] ) ) {
          $return = "File is valid, and was successfully uploaded.\n";
          var_dump( $savedfile );
      } else {
          /**
           * Error generated by _wp_handle_upload()
           * @see _wp_handle_upload() in wp-admin/includes/file.php
           */
          $return = $savedfile['error'];
      }
      $wpdb->update($table_name, array(
                                'time' => date('Y-m-d H:m:s'),
                                $type => $item
                                ),
                                array('id' => 1),
                                array(
                                '%s',
                                '%s'));

      if ($type == 'xml_url') {

        $xml = getXML();
        print __LINE__ . ': getXML() :: ' . $xml[0]->xml_url . '<br>';

        $content = getContent($xml[0]->xml_url);
        //print_r($content);
        saveXML($content);
      }

      //set_transient( 'mapgroove_xml', $content, 60*60 );
      $return = '';
      //$return .= $content;
    }

  }
}
 else {
  $return = $type;
}

echo $return;


