<?php


include_once($_SERVER['DOCUMENT_ROOT'] . '/wp-config.php');

$return = '';
if (count($_REQUEST) > 0) {
  foreach ($_REQUEST as $type => $item) {
    if ($type == 'xml_url') {
      global $wpdb;


      $table_name = $wpdb->prefix . "mapgroove";

      $wpdb->query(
               "truncate $table_name"
      );

// #######


// #######


      if ( $savedfile && ! isset( $savedfile['error'] ) ) {
          $return = "File is valid, and was successfully uploaded.\n";
          var_dump( $savedfile );
      } else {
          /**
           * Error generated by _wp_handle_upload()
           * @see _wp_handle_upload() in wp-admin/includes/file.php
           */
          $return = $savedfile['error'];
      }



      $wpdb->insert($table_name, array(
                                'time' => date('Y-m-d H:m:s'),
                                'xml_url' => $item
                                ),array(
                                '%s',
                                '%s')
        );

      $xml = getXML();
      $content = getContent($xml[0]->xml_url);

      saveXML($content);
      //set_transient( 'mapgroove_xml', $content, 60*60 );
      $return = 'Path added.';
      //$return .= $content;
    }
  }
}
 else {
  $return = 'nope';
}

echo $return;


